defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: 
  password: 

development:
  <<: *defaults
  database: dinosaur-development

test:
  <<: *defaults
  database: dinosaur-test

production:
  <<: *defaults
  database: dinosaur-production
